/*
 * Generated by ASN.1 Java Compiler (http://www.asnlab.org/)
 * From ASN.1 module "MyHTTP"
 */
package ans.test.MyHTTP;

import java.io.*;
import org.asnlab.asndt.runtime.conv.*;
import org.asnlab.asndt.runtime.type.AsnType;
import org.asnlab.asndt.runtime.value.BitString;

public class Standards extends BitString {

	public static final int html = 3;
	public static final int plain_text = 1;
	public static final int gif = 2;
	public static final int jpeg = 0;

	public Standards(byte[] bytes, byte unusedBits) {
		super(bytes, unusedBits);
	}

	public Standards(int size) {
		super(size);
	}

	public Standards() {
		super(0);
	}

	public boolean getHtml(){
		return getBit(html);
	}

	public void setHtml(){
		setBit(html, true);
	}

	public void clearHtml(){
		setBit(html, false);
	}

	public boolean getPlain_text(){
		return getBit(plain_text);
	}

	public void setPlain_text(){
		setBit(plain_text, true);
	}

	public void clearPlain_text(){
		setBit(plain_text, false);
	}

	public boolean getGif(){
		return getBit(gif);
	}

	public void setGif(){
		setBit(gif, true);
	}

	public void clearGif(){
		setBit(gif, false);
	}

	public boolean getJpeg(){
		return getBit(jpeg);
	}

	public void setJpeg(){
		setBit(jpeg, true);
	}

	public void clearJpeg(){
		setBit(jpeg, false);
	}

	public boolean equals(Object obj) {
		if(!(obj instanceof Standards)){
			return false;
		}
		return TYPE.equals(this, obj, CONVERTER);
	}

	public void print(PrintStream out) {
		TYPE.print(this, CONVERTER, out);
	}


	public final static AsnType TYPE = MyHTTP.type(65539);

	public final static AsnConverter CONVERTER;

	static {
		CONVERTER = new ReflectionBitStringConverter(Standards.class);
	}


}
