/*
 * Generated by ASN.1 Java Compiler (http://www.asnlab.org/)
 * From ASN.1 module "MyHTTP"
 */
package ans.test.MyHTTP;

import org.asnlab.asndt.runtime.conv.AsnConverter;
import org.asnlab.asndt.runtime.conv.StringConverter;
import org.asnlab.asndt.runtime.type.AsnType;

public class Url {


	public final static AsnType TYPE = MyHTTP.type(65537);

	public final static AsnConverter CONVERTER = StringConverter.INSTANCE;



}
