spring:
  profiles: web-core
  application:
    name: web-core
  http:
    log-request-details: true

#  logging:
#    level:
#      org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE



external-communication-core:
  serviceExecuteTimeoutSecond: 30
  http11Protocol:
    maxKeepAliveRequests: 1
    connectionTimeout: 10000
project:
  properties:
    angular-path: classpath:/webapp
